grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2

model_selection:    
  module_0:
    class: SVC
    module: sklearn.svm
    C: 1.0
    kernel: rbf
    degree: 3
    gamma: scale
    random_state: None
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false


 module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    n_estimators: 100
    criterion: gini
    max_depth: None
    min_samples_split: 2
    max_leaf_nodes: None
    max_features: sqrt
    verbose: 0
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6